apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
  namespace: istio-system
spec:
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Endpoints
metadata:
  name: keycloak-service
  namespace: istio-system
subsets:
  - addresses:
      - ip: "100.114.236.95"
    ports:
      - name: http
        port: 8080


