apiVersion: v1
kind: Service
metadata:
  name: postgres-service-db
spec:
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: Endpoints
metadata:
  name: postgres-service-db
subsets:
  - addresses:
      - ip: "192.168.122.155" #db address
    ports:
      - port: 5432