services:
  redis:
#    image: redis:7-alpine
    image: redislabs/redisgears
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "secret"]

  redis-insight:
    image: redis/redisinsight:latest
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - redis-insight:/data

volumes:
  redis-insight:

